In [3]:
import torch

# PyTorch

### 1st ex

In [4]:
x = torch.tensor([1.])
y = torch.tensor([10.])

print(x, type(x), x.requires_grad)
print(y, type(y), y.requires_grad)

tensor([1.]) <class 'torch.Tensor'> False
tensor([10.]) <class 'torch.Tensor'> False


In [6]:
k = torch.tensor([2.], requires_grad=True)

print(k, type(k), k.requires_grad)

tensor([2.], requires_grad=True) <class 'torch.Tensor'> True


In [8]:
y_ = k * x

print(y_, type(y_), y_.requires_grad)

tensor([2.], grad_fn=<ThMulBackward>) <class 'torch.Tensor'> True


In [9]:
loss = (y - y_)**2

print(loss, type(loss), loss.requires_grad)

tensor([64.], grad_fn=<PowBackward0>) <class 'torch.Tensor'> True


In [10]:
learning_rate = 0.1
optimizer = torch.optim.SGD([k,], lr=learning_rate)

print(optimizer, type(optimizer))

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.1
    momentum: 0
    nesterov: False
    weight_decay: 0
) <class 'torch.optim.sgd.SGD'>


In [11]:
for _ in range(250):
    print('last_y_ = ', y_)
    y_ = k * x
    print('step_y_ = ', y_)

    print('last_loss = ', loss)
    loss = (y - y_)**2
    print('step_loss = ', loss)

    print('last_k = ', k)
    print('last_grad = ', k.grad) # here starts The Loop # first time no .grad
    optimizer.zero_grad() # clean all grad
    print('zero_grad = ', k.grad)
    loss.backward() # ~backprob~ step
    print('step_grad = ', k.grad)
    print('gradient_descent_value = ', -learning_rate*k.grad)
    print('predicted_step_key = ', k - learning_rate*k.grad)

    optimizer.step()
    print('step_k = ', k)
    print('____________')

last_y_ =  tensor([2.], grad_fn=<ThMulBackward>)
step_y_ =  tensor([2.], grad_fn=<ThMulBackward>)
last_loss =  tensor([64.], grad_fn=<PowBackward0>)
step_loss =  tensor([64.], grad_fn=<PowBackward0>)
last_k =  tensor([2.], requires_grad=True)
last_grad =  None
zero_grad =  None
step_grad =  tensor([-16.])
gradient_descent_value =  tensor([1.6000])
predicted_step_key =  tensor([3.6000], grad_fn=<ThSubBackward>)
step_k =  tensor([3.6000], requires_grad=True)
____________
last_y_ =  tensor([2.], grad_fn=<ThMulBackward>)
step_y_ =  tensor([3.6000], grad_fn=<ThMulBackward>)
last_loss =  tensor([64.], grad_fn=<PowBackward0>)
step_loss =  tensor([40.9600], grad_fn=<PowBackward0>)
last_k =  tensor([3.6000], requires_grad=True)
last_grad =  tensor([-16.])
zero_grad =  tensor([0.])
step_grad =  tensor([-12.8000])
gradient_descent_value =  tensor([1.2800])
predicted_step_key =  tensor([4.8800], grad_fn=<ThSubBackward>)
step_k =  tensor([4.8800], requires_grad=True)
____________
last_y_ =  tensor(

last_loss =  tensor([0.0002], grad_fn=<PowBackward0>)
step_loss =  tensor([0.0002], grad_fn=<PowBackward0>)
last_k =  tensor([9.9876], requires_grad=True)
last_grad =  tensor([-0.0309])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0248])
gradient_descent_value =  tensor([0.0025])
predicted_step_key =  tensor([9.9901], grad_fn=<ThSubBackward>)
step_k =  tensor([9.9901], requires_grad=True)
____________
last_y_ =  tensor([9.9876], grad_fn=<ThMulBackward>)
step_y_ =  tensor([9.9901], grad_fn=<ThMulBackward>)
last_loss =  tensor([0.0002], grad_fn=<PowBackward0>)
step_loss =  tensor([0.0001], grad_fn=<PowBackward0>)
last_k =  tensor([9.9901], requires_grad=True)
last_grad =  tensor([-0.0248])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0198])
gradient_descent_value =  tensor([0.0020])
predicted_step_key =  tensor([9.9921], grad_fn=<ThSubBackward>)
step_k =  tensor([9.9921], requires_grad=True)
____________
last_y_ =  tensor([9.9901], grad_fn=<ThMulBackward>)
step_y_ =  tensor([9.

step_k =  tensor([10.0000], requires_grad=True)
____________
last_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
step_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
last_loss =  tensor([2.2737e-11], grad_fn=<PowBackward0>)
step_loss =  tensor([1.4552e-11], grad_fn=<PowBackward0>)
last_k =  tensor([10.0000], requires_grad=True)
last_grad =  tensor([-0.0000])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0000])
gradient_descent_value =  tensor([7.6294e-07])
predicted_step_key =  tensor([10.0000], grad_fn=<ThSubBackward>)
step_k =  tensor([10.0000], requires_grad=True)
____________
last_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
step_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
last_loss =  tensor([1.4552e-11], grad_fn=<PowBackward0>)
step_loss =  tensor([8.1855e-12], grad_fn=<PowBackward0>)
last_k =  tensor([10.0000], requires_grad=True)
last_grad =  tensor([-0.0000])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0000])
gradient_descent_value =  tensor([5.7220e-07])

step_k =  tensor([10.0000], requires_grad=True)
____________
last_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
step_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
last_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
step_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
last_k =  tensor([10.0000], requires_grad=True)
last_grad =  tensor([-0.0000])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0000])
gradient_descent_value =  tensor([3.8147e-07])
predicted_step_key =  tensor([10.0000], grad_fn=<ThSubBackward>)
step_k =  tensor([10.0000], requires_grad=True)
____________
last_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
step_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
last_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
step_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
last_k =  tensor([10.0000], requires_grad=True)
last_grad =  tensor([-0.0000])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0000])
gradient_descent_value =  tensor([3.8147e-07])

last_grad =  tensor([-0.0000])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0000])
gradient_descent_value =  tensor([3.8147e-07])
predicted_step_key =  tensor([10.0000], grad_fn=<ThSubBackward>)
step_k =  tensor([10.0000], requires_grad=True)
____________
last_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
step_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
last_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
step_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
last_k =  tensor([10.0000], requires_grad=True)
last_grad =  tensor([-0.0000])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0000])
gradient_descent_value =  tensor([3.8147e-07])
predicted_step_key =  tensor([10.0000], grad_fn=<ThSubBackward>)
step_k =  tensor([10.0000], requires_grad=True)
____________
last_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
step_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
last_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
step_loss =  tensor([3.6380e-12], grad_f

last_k =  tensor([10.0000], requires_grad=True)
last_grad =  tensor([-0.0000])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0000])
gradient_descent_value =  tensor([3.8147e-07])
predicted_step_key =  tensor([10.0000], grad_fn=<ThSubBackward>)
step_k =  tensor([10.0000], requires_grad=True)
____________
last_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
step_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
last_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
step_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
last_k =  tensor([10.0000], requires_grad=True)
last_grad =  tensor([-0.0000])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0000])
gradient_descent_value =  tensor([3.8147e-07])
predicted_step_key =  tensor([10.0000], grad_fn=<ThSubBackward>)
step_k =  tensor([10.0000], requires_grad=True)
____________
last_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
step_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
last_loss =  tensor([3.6380e-12], grad_fn=<PowBack

last_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
step_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
last_k =  tensor([10.0000], requires_grad=True)
last_grad =  tensor([-0.0000])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0000])
gradient_descent_value =  tensor([3.8147e-07])
predicted_step_key =  tensor([10.0000], grad_fn=<ThSubBackward>)
step_k =  tensor([10.0000], requires_grad=True)
____________
last_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
step_y_ =  tensor([10.0000], grad_fn=<ThMulBackward>)
last_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
step_loss =  tensor([3.6380e-12], grad_fn=<PowBackward0>)
last_k =  tensor([10.0000], requires_grad=True)
last_grad =  tensor([-0.0000])
zero_grad =  tensor([0.])
step_grad =  tensor([-0.0000])
gradient_descent_value =  tensor([3.8147e-07])
predicted_step_key =  tensor([10.0000], grad_fn=<ThSubBackward>)
step_k =  tensor([10.0000], requires_grad=True)
____________
last_y_ =  tensor([10.0000], grad_fn=<ThMu

### task

In [24]:
x1 = torch.tensor([2.])
x2 = torch.tensor([3.])

print(x1, type(x1), x1.requires_grad)
print(x2, type(x2), x2.requires_grad)

tensor([2.]) <class 'torch.Tensor'> False
tensor([3.]) <class 'torch.Tensor'> False


In [25]:
k1 = torch.tensor([.12], requires_grad=True)
k2 = torch.tensor([.18], requires_grad=True)

print(k1, type(k1), k1.requires_grad)

tensor([0.1200], requires_grad=True) <class 'torch.Tensor'> True


In [26]:
res = k1*x1 + k2*x2

print(res, type(res), res.requires_grad)

tensor([0.7800], grad_fn=<ThAddBackward>) <class 'torch.Tensor'> True


In [27]:
loss = res**2

In [28]:
learning_rate = 0.01
optimizer = torch.optim.SGD([k1, k2], lr=learning_rate)

print(optimizer, type(optimizer)) # Parameter of SGD optimizer -> lr=learning_rate

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.01
    momentum: 0
    nesterov: False
    weight_decay: 0
) <class 'torch.optim.sgd.SGD'>


In [29]:
for _ in range(251):
    res = k1*x1 + k2*x2
    loss = (res - 0)**2
    optimizer.zero_grad() # clean all grad
    loss.backward() # ~backprob~ step
    optimizer.step()
    
    if _ % 50 == 0:
        print('step = ', _)
        print('res = ', res)
        print('step_loss', loss)
        print('step_grad = ', k1.grad, k2.grad)
        print('step_k = ', k1, k2)
        print('____________')

step =  0
res =  tensor([0.7800], grad_fn=<ThAddBackward>)
step_loss tensor([0.6084], grad_fn=<PowBackward0>)
step_grad =  tensor([3.1200]) tensor([4.6800])
step_k =  tensor([0.0888], requires_grad=True) tensor([0.1332], requires_grad=True)
____________
step =  50
res =  tensor([2.2578e-07], grad_fn=<ThAddBackward>)
step_loss tensor([5.0975e-14], grad_fn=<PowBackward0>)
step_grad =  tensor([9.0311e-07]) tensor([1.3547e-06])
step_k =  tensor([2.3979e-08], requires_grad=True) tensor([3.9706e-08], requires_grad=True)
____________
step =  100
res =  tensor([6.5281e-14], grad_fn=<ThAddBackward>)
step_loss tensor([4.2616e-27], grad_fn=<PowBackward0>)
step_grad =  tensor([2.6112e-13]) tensor([3.9169e-13])
step_k =  tensor([-0.0000], requires_grad=True) tensor([1.1501e-09], requires_grad=True)
____________
step =  150
res =  tensor([8.8818e-16], grad_fn=<ThAddBackward>)
step_loss tensor([7.8886e-31], grad_fn=<PowBackward0>)
step_grad =  tensor([3.5527e-15]) tensor([5.3291e-15])
step_k =  tenso

### Linear Regression

In [30]:
x = torch.tensor([ 1.,  2.,  3.,  4.,  5., 6., 7.])
y = torch.tensor([13., 19., 25., 29., 35., 38., 43.])

print(x, type(x), x.requires_grad)
print(y, type(y), y.requires_grad)

tensor([1., 2., 3., 4., 5., 6., 7.]) <class 'torch.Tensor'> False
tensor([13., 19., 25., 29., 35., 38., 43.]) <class 'torch.Tensor'> False


In [33]:
k = torch.tensor([2.], requires_grad=True)
b = torch.tensor([0.], requires_grad=True)

print(k, type(k), k.requires_grad)

tensor([2.], requires_grad=True) <class 'torch.Tensor'> True


In [34]:
y_ = k*x + b

print(y_, type(y_), y_.requires_grad)

tensor([ 2.,  4.,  6.,  8., 10., 12., 14.], grad_fn=<ThAddBackward>) <class 'torch.Tensor'> True
