In [118]:
import torch

In [119]:
x = torch.tensor([1.])
y = torch.tensor([10.])

print(x, type(x), x.requires_grad)

tensor([ 1.]) <class 'torch.Tensor'> False


In [120]:
k = torch.tensor([2.], requires_grad=True)

print(k, type(k), k.requires_grad)

tensor([ 2.]) <class 'torch.Tensor'> True


In [121]:
y_ = k * x

print(y_, type(y_), y_.requires_grad)

tensor([ 2.]) <class 'torch.Tensor'> True


In [122]:
loss = (y - y_)**2

print(loss, type(loss), loss.requires_grad)

tensor([ 64.]) <class 'torch.Tensor'> True


In [123]:
learning_rate = 0.1
optimizer = torch.optim.SGD([k,], lr=learning_rate)

print(optimizer, type(optimizer)) # Parameter of SGD optimizer -> lr=learning_rate

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.1
    momentum: 0
    nesterov: False
    weight_decay: 0
) <class 'torch.optim.sgd.SGD'>


In [125]:
# Learning Loop # yes, yes, you can do next:
# for _ in range(n):

print('last_y_ = ', y_)
y_ = k * x
print('step_y_ = ', y_)

print('last_loss = ', loss)
loss = (y - y_)**2
print('step_loss = ', loss)

print('last_k = ', k)
print('last_grad = ', k.grad) # here starts The Loop # first time no .grad
optimizer.zero_grad() # clean all grad
print('zero_grad = ', k.grad)
loss.backward() # ~backprob~ step
print('step_grad = ', k.grad)
print('gradient_descent_value = ', -learning_rate*k.grad)
print('predicted_step_key = ', k - learning_rate*k.grad)

optimizer.step()
print('step_k = ', k)
print('____________')

step_y_ =  tensor([ 9.9078])
step_loss =  tensor(1.00000e-03 *
       [ 8.5070])
last_grad =  tensor([-0.2306])
zero_grad =  tensor([ 0.])
step_grad =  tensor([-0.1845])
gradient_descent_value =  tensor(1.00000e-02 *
       [ 1.8447])
predicted_step_key =  tensor([ 9.9262])
step_k =  tensor([ 9.9262])
____________
